# helm install airflow apache-airflow/airflow \
#   --namespace airflow \
#   --create-namespace \
#   -f values.yaml
#   --set executor=KubernetesExecutor \
#   --set images.airflow.repository=romansvetkin/airflow-dbt-test \
#   --set images.airflow.tag=latest

executor: KubernetesExecutor
workers:
  resources:
    requests:
      memory: 512Mi
      cpu: 200m
    limits:
      memory: 1Gi
      cpu: '0.5'
scheduler:
  resources:
    requests:
      memory: 512Mi
      cpu: 200m
    limits:
      memory: 1Gi
      cpu: '0.5'
web:
  resources:
    requests:
      memory: 512Mi
      cpu: 200m
    limits:
      memory: 1Gi
      cpu: '0.5'
statsd:
  resources:
    requests:
      memory: 512Mi
      cpu: 200m
    limits:
      memory: 1Gi
      cpu: '0.5'
dags:
  mountPath: /Users/rsvetk01/Desktop/start/branches_to_publish/branches_to_publish/dbt-airflow/airflow/dags
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
