my_dbt_project:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: "{{ env_var('DB_HOST') }}"
      port: 5432
      user: "{{ env_var('DB_USERNAME') }}"
      pass: "{{ env_var('DB_PASSWORD') }}"
      dbname: "{{ env_var('DB_DATABASE') }}"
      schema: public
  target: dev
